### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'

### ISSUE THREAD

**Issue by bft24h** [omkarcloud/google-maps-scraper#1]
The error appears when I run the command python main.py
`C:\Users\Admin\Desktop\WPF TCT\my-bose-project>python main.py
Task Started
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\WPF TCT\my-bose-project\main.py", line 7, in <module>
    t.begin_task()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\base_task.py", line 144, in begin_task
    return run_task(False, 0)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\base_task.py", line 110, in run_task
    driver = self.create_driver(config)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\base_task.py", line 43, in create_driver
    return create_driver(config)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\create_driver.py", line 195, in create_driver
    driver = retry_if_is_error(
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\utils.py", line 87, in retry_if_is_error
    raise e
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\utils.py", line 80, in retry_if_is_error
    created_result = func()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\bose\create_driver.py", line 184, in run
    driver = BossDriver(
TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'`

**Comment by Chetan11-dev** [comment]
@bft24h Selenium Version?

**Comment by bft24h** [comment]
git clone https://github.com/omkarcloud/google-maps-scraper
cd google-maps-scraper
python -m pip install -r requirements.txt
python main.py
I use this script.

**Comment by Alexeiyaganov** [comment]
have the same problem!

**Comment by bft24h** [comment]
> @bft24h Selenium Version?

Chromedriver 114.0.5735.90 
Version google chrome  114.0.5735.110

**Comment by Chetan11-dev** [comment]
```pip show selenium ``` Output?

**Comment by bft24h** [comment]
Name: selenium
Version: 4.10.0
Summary:
Home-page: https://www.selenium.dev
Author:
Author-email:
License: Apache 2.0
Location: c:\users\admin\appdata\roaming\python\python39\site-packages
Requires: certifi, trio, trio-websocket, urllib3
Required-by: bose, undetected-chromedriver

**Comment by Chetan11-dev** [comment]
Run this Command and issue will be resolved. ```python -m pip install selenium==4.5.0 --force```

**Comment by bft24h** [comment]
> Run this Command and issue will be resolved. `python -m pip install selenium==4.5.0 --force`

it works. thanks bro.

**Comment by Chetan11-dev** [comment]
@bft24h I am a full stack developer, professional web scraper. Please see my portfolio at https://dev.to/chetanan/chetan-jains-portfolio-cl6 and let me know if you need help in regard to your projects. I would be happy to help.
