### ISSUE TITLE
ModuleNotFoundError: No module named 'unidecode'

### ISSUE THREAD

**Issue by salmansarwar5102** [omkarcloud/google-maps-scraper#119]
Traceback (most recent call last):
  File "/home/sam/site/google-maps-scraper/main.py", line 1, in <module>
    from src import Gmaps
  File "/home/sam/site/google-maps-scraper/src/__init__.py", line 1, in <module>
    from .gmaps import Gmaps
  File "/home/sam/site/google-maps-scraper/src/gmaps.py", line 3, in <module>
    from src import scraper
  File "/home/sam/site/google-maps-scraper/src/scraper.py", line 7, in <module>
    from src.utils import convert_unicode_dict_to_ascii_dict, unique_strings
  File "/home/sam/site/google-maps-scraper/src/utils.py", line 2, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

**Comment by Chetan11-dev** [comment]
Kindly Run
python -m pip install botasaurus --upgrade
python -m pip install -r requirements.txt
