### ISSUE TITLE
TypeError: object of type 'NoneType' has no len() | 'els' has a None Value

### ISSUE THREAD

**Issue by geniecode1** [omkarcloud/google-maps-scraper#13]
It seems like there's a problem with the **'els'** elements. They have a **'None**' value so they're probably not getting identified correctly.

Traceback (most recent call last):
  File "C:\Users\said\AppData\Local\Programs\Python\Python39\lib\site-packages\bose\base_task.py", line 208, in run_task
    result = self.run(driver, data)
  File "C:\Users\said\Desktop\My_Files\google-maps-scraper-master\src\scrape_google_maps_links_task.py", line 101, in run
    links  = get_links()
  File "C:\Users\said\Desktop\My_Files\google-maps-scraper-master\src\scrape_google_maps_links_task.py", line 84, in get_links
    scroll_till_end(1)
  File "C:\Users\said\Desktop\My_Files\google-maps-scraper-master\src\scrape_google_maps_links_task.py", line 81, in scroll_till_end
    if len(els) >= max_results:
**TypeError: object of type 'NoneType' has no len()**

**Comment by Chetan11-dev** [comment]
👋 Hello geniecode1,
I'm unable to assist you with your issue due to my priorities. I encourage you to try resolving the issue by yourself and post the solution to help the community.
Thanks for your understanding.
