### ISSUE TITLE
Error when trying to install requirements, help!

### ISSUE THREAD

**Issue by negatifstoner** [omkarcloud/google-maps-scraper#135]
Getting this error when trying to install requirements, what am i doing wrong?
```
python -m pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/Users/S2B/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Unidecode
  Downloading Unidecode-1.2.0-py2.py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 1.9 MB/s 
Collecting geonamescache
  Downloading geonamescache-2.0.0.tar.gz (25.6 MB)
     |████████████████████████████████| 25.6 MB 14.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-guqf4A/geonamescache/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-guqf4A/geonamescache/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-nkxEFh
         cwd: /private/tmp/pip-install-guqf4A/geonamescache/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-guqf4A/geonamescache/setup.py", line 2, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
iMac-de-i:google-maps-scraper S2B$ 

```

**Comment by Chetan11-dev** [comment]
Kindly run 
python -m pip install pathlib

**Comment by negatifstoner** [comment]
Still getting the same error the pathlib installed succesfully tho, I am using my work mac, I will go try it in my pc and see if i can figure what the problem is. if there is anything u can help me with it would be much appreciated!

**Comment by Chetan11-dev** [comment]
I researched on it and based on stackoverflow, it is due to old python version. (https://stackoverflow.com/questions/62910916/importerror-no-module-named-pathlib)
Kindly update to python 3.8+ and let me know if it occurs
