### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Codexsuprememe456** [omkarcloud/google-maps-scraper#14]
The 'els' variable, which is supposed to contain a list of elements, is None in the 'extract_links()' function

Traceback (most recent call last):
  File "C:\Users\yravi\AppData\Roaming\Python\Python311\site-packages\bose\base_task.py", line 117, in run_task
    self.run(driver)
  File "C:\Users\yravi\Documents\google-maps-scraper-master\src\scraper.py", line 249, in run
    result = get_data(driver, query, chotu_address_hierarchy, chotu_shop_category)  # Call the get_data function
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yravi\Documents\google-maps-scraper-master\src\scraper.py", line 233, in get_data
    links = get_links(query)
            ^^^^^^^^^^^^^^^^
  File "C:\Users\yravi\Documents\google-maps-scraper-master\src\scraper.py", line 139, in get_links
    links = extract_links(els)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yravi\Documents\google-maps-scraper-master\src\scraper.py", line 135, in extract_links
    return list(map(extract_link, elements))

**Comment by Chetan11-dev** [comment]
How to reproduce?

**Comment by Chetan11-dev** [comment]
Use Latest Version. Also, let me know if you have need of scraping a website or someone you know needs scraping services.

**Comment by Codexsuprememe456** [comment]
okay , thanks mate
