### ISSUE TITLE
Error when trying to run app

### ISSUE THREAD

**Issue by Laszlobercsenyi** [omkarcloud/google-maps-scraper#147]
C:\magic2\google-maps-scraper-master>python run.py
Bottle v0.12.25 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

> frontend@1.0.0 start
> next start

(node:6624) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Could not find a production build in the 'C:\magic2\google-maps-scraper-master\frontend\.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (C:\magic2\google-maps-scraper-master\frontend\node_modules\next\dist\server\next-server.js:169:23)
    at new Server (C:\magic2\google-maps-scraper-master\frontend\node_modules\next\dist\server\base-server.js:58:29)
    at new NextNodeServer (C:\magic2\google-maps-scraper-master\frontend\node_modules\next\dist\server\next-server.js:70:9)
    at NextServer.createServer (C:\magic2\google-maps-scraper-master\frontend\node_modules\next\dist\server\next.js:140:16)
    at async C:\magic2\google-maps-scraper-master\frontend\node_modules\next\dist\server\next.js:149:31
Traceback (most recent call last):
  File "C:\magic2\google-maps-scraper-master\run.py", line 5, in <module>
    run_server()
  File "C:\Python312\Lib\site-packages\botasaurus_server\run_server.py", line 23, in run_server
    run_frontend()
  File "C:\Python312\Lib\site-packages\botasaurus_server\run_server.py", line 11, in run_frontend
    subprocess.check_call("npm run start", shell=True, cwd=frontend_dir)
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'npm run start' returned non-zero exit status 1.

C:\magic2\google-maps-scraper-master>

**Comment by Laszlobercsenyi** [comment]
Running on WIndows 10  Native,  Just installed everything through CMD and Powershell. all the requirements

**Comment by Laszlobercsenyi** [comment]
Im trying to figure out how to upgrade these modules i do not even know yet what environment is it...

**Comment by Laszlobercsenyi** [comment]
Okay   I think i have discovered where it came from:  
It looks like like it was not built perfectly becaouse rm as command not really exists on my pc i will try to fix






Installing frontend dependencies...

up to date, audited 770 packages in 8s

203 packages are looking for funding
  run `npm fund` for details

17 vulnerabilities (7 moderate, 7 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> frontend@1.0.0 build
> rm -f public/themes/*.min.css && next build --no-lint

'rm' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\magic2\google-maps-scraper-master\run.py", line 5, in <module>
    run_server()
  File "C:\Python312\Lib\site-packages\botasaurus_server\run_server.py", line 31, in run_server
    install()
  File "C:\Python312\Lib\site-packages\botasaurus_server\run_server.py", line 17, in install
    subprocess.check_call("npm install && npm run build", shell=True, cwd=frontend_dir)
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'npm install && npm run build' returned non-zero exit status 1.

C:\magic2\google-maps-scraper-master>

**Comment by Chetan11-dev** [comment]
Resolved it, Kindly use the latest version.
