### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by Iamtheoldman** [omkarcloud/google-maps-scraper#175]
a7 % python run.py
Traceback (most recent call last):
  File "/Users/dameonjensen/Downloads/omkarcloud-google-maps-scraper-pro-cfdd8a4d052f8f0deffa755ef01c2879230dcfa7/run.py", line 1, in <module>
    import backend.scrapers
  File "/Users/dameonjensen/Downloads/omkarcloud-google-maps-scraper-pro-cfdd8a4d052f8f0deffa755ef01c2879230dcfa7/backend/scrapers.py", line 2, in <module>
    from src.gmaps import get_places
  File "/Users/dameonjensen/Downloads/omkarcloud-google-maps-scraper-pro-cfdd8a4d052f8f0deffa755ef01c2879230dcfa7/src/gmaps.py", line 2, in <module>
    from botasaurus.request import request
ModuleNotFoundError: No module named 'botasaurus.request'
(anaconda3) (base) dameonjensen@Dameons-Laptop omkarcloud-google-maps-scraper-pro-cfdd8a4d052f8f0deffa755ef01c2879230dcfa7 %

**Comment by Chetan11-dev** [comment]
Run 
python -m pip install --upgrade pip
python -m pip install bota botasaurus botasaurus_api botasaurus_driver bota botasaurus-proxy-authentication botasaurus_server --upgrade
Reclone and install repository
