### ISSUE TITLE
Assertion Error when scraping

### ISSUE THREAD

**Issue by amoham42** [omkarcloud/google-maps-scraper#177]
This happens without any warning and the task does not stop, but also doesnt show any progress.

Traceback (most recent call last):
  File "Desktop/scrap/src/scraper.py", line 111, in scrape_reviews
    result = scraper.scrape_reviews(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "Desktop/scrap/src/reviews_scraper.py", line 543, in scrape_reviews
    self._handle_place_exception(response_text, url_name, i)
  File "Desktop/scrap/src/reviews_scraper.py", line 329, in _handle_place_exception
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/place_Upland_request_37_2024-06-02_18-26-44_311844.html'
127.0.0.1 - - [02/Jun/2024 18:26:45] "POST /api/ui/tasks/is-any-task-updated HTTP/1.1" 200 17
127.0.0.1 - - [02/Jun/2024 18:26:46] "POST /api/ui/tasks/is-any-task-updated HTTP/1.1" 200 17
127.0.0.1 - - [02/Jun/2024 18:26:47] "POST /api/ui/tasks/is-any-task-updated HTTP/1.1" 200 17
output/place_Carbone New York_request_2_2024-06-02_18-26-47_988632.html
Traceback (most recent call last):
  File "Desktop/scrap/src/reviews_scraper.py", line 538, in scrape_reviews
    assert isinstance(reviews_soup, list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Desktop/scrap/src/scraper.py", line 111, in scrape_reviews
    result = scraper.scrape_reviews(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "Desktop/scrap/src/reviews_scraper.py", line 543, in scrape_reviews
    self._handle_place_exception(response_text, url_name, i)
  File "Desktop/scrap/src/reviews_scraper.py", line 329, in _handle_place_exception
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/place_Carbone New York_request_2_2024-06-02_18-26-47_988632.html'

**Comment by Chetan11-dev** [comment]
resolved
