### ISSUE TITLE
 'Window': Request cannot be constructed 

### ISSUE THREAD

**Issue by widada** [omkarcloud/google-maps-scraper#184]
main-b988c55a89aca51c.js:1 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /_next/data/eo0pNmiwooIdaYWXKre6v/output.json
    at K (main-b988c55a89aca51c.js:1:56759)
    at d (main-b988c55a89aca51c.js:1:57382)
    at J (main-b988c55a89aca51c.js:1:58253)
    at main-b988c55a89aca51c.js:1:70134
    at main-b988c55a89aca51c.js:1:116138
    at Object.next (main-b988c55a89aca51c.js:1:116243)
    at r (main-b988c55a89aca51c.js:1:882)
    at u (main-b988c55a89aca51c.js:1:1087)
    at main-b988c55a89aca51c.js:1:1146
    at new Promise (<anonymous>)

**Comment by Chetan11-dev** [comment]
output of command 
```
node -v
```
