### ISSUE TITLE
Task failed Failed to connect to Chrome URL

### ISSUE THREAD

**Issue by dlusson** [omkarcloud/google-maps-scraper#193]
Hi,

I installed the pro version on an hetzner cloud server, everything running fine including interface, but when i try to run one task i get this error, i installed chrome and chromedriver on the vps too (same version and compatible)

When i run it on my pc it works but not on the vps.

Thanks in advance

`Traceback (most recent call last):
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_server/task_executor.py", line 150, in run_task
    result = fn(
             ^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus/request_decorator.py", line 196, in wrapper_requests
    current_result = run_task(data_item, False, 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus/request_decorator.py", line 164, in run_task
    raise error
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus/request_decorator.py", line 110, in run_task
    result = func(reqs, data)
             ^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/src/gmaps.py", line 331, in google_maps_scraper
    places_obj = scraper.scrape_places(place_data,)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus/browser_decorator.py", line 275, in wrapper_browser
    current_result = run_task(data_item, False, 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus/browser_decorator.py", line 162, in run_task
    driver = Driver(headless=evaluated_headless, proxy=evaluated_proxy, profile=evaluated_profile, tiny_profile=tiny_profile, block_images=block_images, block_images_and_css=block_images_and_css, wait_for_complete_page_load=wait_for_complete_page_load, extensions=evaluated_extensions, arguments=args, user_agent=evaluated_user_agent, window_size=evaluated_window_size, lang=evaluated_lang, beep=beep)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/driver.py", line 1273, in __init__
    self._browser: Browser = self._run(start(self.config))
                                       ^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/util.py", line 90, in start
    return Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/browser.py", line 123, in create
    instance.start()
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/browser.py", line 271, in start
    self.create_chrome_with_retries(exe, params)
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/browser.py", line 321, in create_chrome_with_retries
    run()
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/retry_on_error.py", line 47, in wrapper
    raise e
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/retry_on_error.py", line 22, in wrapper
    created_result = func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/browser.py", line 315, in run
    self.info = ensure_chrome_is_alive(chrome_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/google-maps-scraper/venv/lib/python3.12/site-packages/botasaurus_driver/core/browser.py", line 55, in ensure_chrome_is_alive
    raise Exception(f"Failed to connect to Chrome URL: {url}.")
Exception: Failed to connect to Chrome URL: http://127.0.0.1:38321/json/version.`

**Comment by Chetan11-dev** [comment]
Kindly follow https://github.com/omkarcloud/botasaurus#how-to-run-scraper-in-virtual-machine to run it in Server
