### ISSUE TITLE
Big query

### ISSUE THREAD

**Issue by derekemm** [omkarcloud/google-maps-scraper#219]
hi,

I am getting the following error on high queries. Can you help me with this?
![Ekran Alıntısı](https://github.com/user-attachments/assets/2db131ae-2f47-4add-9cb7-f45d77389130)

**Comment by Chetan11-dev** [comment]
Please Reinstall, we release a bug fix

**Comment by derekemm** [comment]
![image](https://github.com/user-attachments/assets/14e2c0c1-7b92-4827-8cb7-c2f651fbb5f7)

Unfortunately it continues to give the same error.

**Comment by Chetan11-dev** [comment]
please download and reinstall again, as we release fix. 
Also share how you cause this error?

**Comment by derekemm** [comment]
I have a search of 36628 records. there is no problem in the first run. But when I turn off the PC and turn it on again, the previous error appears and the output screen freezes like the picture below 

![image](https://github.com/user-attachments/assets/c31eb9f7-c563-4b64-abff-627afa9abc51)

**Comment by Chetan11-dev** [comment]
I suggest resetting the app and starting from scratch again, by going to 
Support > Factory Reset App and Clear All Data. 
This error should not reoccur again, given that you followed the previous comment I told you

**Comment by derekemm** [comment]
The error I mentioned has been fixed. Thank you.

Now I am getting a different error
![image](https://github.com/user-attachments/assets/433d5f17-28c3-437f-aa93-ba9e3dc3a169)

SyntaxError: Bad control character in string literal in JSON at position 3145728 (line 103498 column 48)
    at JSON.parse (<anonymous>)
    at o.refresh (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:193450)
    at new o (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:193300)
    at new s (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:194062)
    at c (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:169287)
    at h.saveCachedTask (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:169621)
    at t.TaskExecutor.markTaskAsSuccess (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:163256)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.TaskExecutor.runTask (C:\Users\winserver\AppData\Local\Programs\googlemapsextractor\resources\app.asar\dist\main\main.js:2:161640)

**Comment by Chetan11-dev** [comment]
Please download and use latest version, let me know if it works?
