### ISSUE TITLE
Can't get reviews when using "place_id" link

### ISSUE THREAD

**Issue by dustinpham235** [omkarcloud/google-maps-scraper#224]
Hi, thanks for the great tool!

I run into issues with reviews scraping when using this type of link: https://www.google.com/maps/search/?api=1&query=place_id:ChIJr2hOBDetNTERGJXIZ83vvBc&query_place_id=ChIJr2hOBDetNTERGJXIZ83vvBc

Unselect "reviews" option works though. Here's the error. Thanks for your help!

```
TypeError: Cannot read properties of undefined (reading 'place_id')
    at /Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:6687297
    at Array.find (<anonymous>)
    at pA (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:6687286)
    at CA (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:6688291)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:6688760)
    at async S (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:341548)
    at async n (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:342678)
    at async t.TaskExecutor.runTask (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:290467)
```

**Comment by Chetan11-dev** [comment]
Fixed, download and use latest version.
Thanks :)

**Comment by TimKJones** [comment]
I'm running into the same bug.

**This was my input URL:** https://www.google.com/maps/search/plumbers+near+nashville+tn/@36.0559074,-87.5041467,9z/data=!3m1!4b1?entry=ttu&g_ep=EgoyMDI1MDQwOC4wIKXMDSoJLDEwMjExNDUzSAFQAw%3D%3D

I get the same error when the input (in the "Search queries" text input) is just the search query "plumbers in nashville tn"

**This was the output:**
```
TypeError: Cannot read properties of undefined (reading 'place_id')
    at /Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:8072430
    at Array.find (<anonymous>)
    at sy (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:8072419)
    at ly (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:8073424)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:8073939)
    at async S (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:5091593)
    at async n (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:5092723)
    at async t.TaskExecutor.runTask (/Applications/Google Maps Extractor.app/Contents/Resources/app.asar/dist/main/main.js:2:5615679)
```
