### ISSUE TITLE
Traceback (most recent call last) / Bose / ChromeDriver

### ISSUE THREAD

**Issue by bakill3** [omkarcloud/google-maps-scraper#25]
Task Started
[INFO] Downloading Driver for Chrome Version 116 in build/ directory. This is a one-time process. Download in progress...
WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] O sistema não conseguiu localizar o caminho especificado: 'build/116/chromedriver.exe' -> 'build/chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deost\OneDrive\Ambiente de Trabalho\Google Maps Scraper\google-maps-scraper\main.py", line 19, in <module>
    launch_tasks(*tasks_to_be_run)
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\launch_tasks.py", line 54, in launch_tasks
    current_output = task.begin_task(current_data, task_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 214, in begin_task
    final = run_task(False, 0)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 155, in run_task
    create_directories(self.task_path)
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 99, in create_directories
    _download_driver()
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 34, in _download_driver
    download_driver()
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\download_driver.py", line 50, in download_driver
    move_driver()
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\download_driver.py", line 39, in move_driver
    move_chromedriver()
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\download_driver.py", line 38, in move_chromedriver
    shutil.move(src_path, dest_path)
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\deost\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'build/116/chromedriver.exe'

**Comment by Chetan11-dev** [comment]
See https://github.com/omkarcloud/google-maps-scraper#-i-am-seeing-error-like-filenotfounderror-errno-2-no-such-file-or-directory-build115chromedriverexe-when-running-python-mainpy

**Comment by Chetan11-dev** [comment]
Run Command to update dependencies "python -m pip install bose --force"
