### ISSUE TITLE
Getting error while executing

### ISSUE THREAD

**Issue by deepaksethi141** [omkarcloud/google-maps-scraper#29]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    launch_tasks(*tasks_to_be_run)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bose\launch_tasks.py", line 54, in launch_tasks
    current_output = task.begin_task(current_data, task_config)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bose\base_task.py", line 219, in begin_task
    final = run_task(False, 0)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bose\base_task.py", line 160, in run_task
    create_directories(self.task_path)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bose\base_task.py", line 104, in create_directories
    _download_driver()
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bose\base_task.py", line 33, in _download_driver
    from .download_driver import download_driver
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bose\download_driver.py", line 1, in <module>
    import chromedriver_autoinstaller_fix
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\chromedriver_autoinstaller_fix\__init__.py", line 7, in <module>
    from . import utils
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\chromedriver_autoinstaller_fix\utils.py", line 19, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by donutdespair** [comment]
Since you're getting "ModuleNotFoundError: No module named 'packaging'", have you tried upgrading pip and installing packaging?

https://stackoverflow.com/questions/42222096/no-module-named-packaging

**Comment by deepaksethi141** [comment]
I am a novice at this, just an end user please elaborate

**Comment by donutdespair** [comment]
You are missing a module called "packaging" that is required to run the scraper.

In the terminal where you are running this program, upgrade pip:
`pip install --upgrade pip`
and install packaging:
`pip install packaging`

**Comment by Chetan11-dev** [comment]
yes, follow @donutdespair instructions
