### ISSUE TITLE
Max retries exceeded with url: /backend/ipinfo/ 

### ISSUE THREAD

**Issue by sh3ll4rpw** [omkarcloud/google-maps-scraper#37]
I got a fresh IP. Scraped 120 queries. Had a 2 weeks break and now when scraping I get the following error after each query. Before it was working.
```
Traceback (most recent call last):
  File "/home/arch/.local/lib/python3.11/site-packages/bose/ip_utils.py", line 7, in find_ip_details
    response = requests.get(url, timeout=10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send 
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 565, in send 
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.omkar.cloud', port=443): Max retries exceeded with url: /backend/ipinfo/ (Caused by NewConnection
Error('<urllib3.connection.HTTPSConnection object at 0x7fbfae708c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Closing Browser
Closed Browser
View Final Screenshot at tasks/546/final.png
View written JSON file at output/all.json 
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
Launched Browser
Fetched 8 links.
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Launched Browser
Done: SECURE ENERGY
Done: Secure Energy
```

**Comment by Chetan11-dev** [comment]
It will not occur from now onwards.
