### ISSUE TITLE
TaskConfig.__init__() got an unexpected keyword argument 'log_time'

### ISSUE THREAD

**Issue by 007-JB** [omkarcloud/google-maps-scraper#38]
I've got the following for the pro version: not running:

$ python main.py
Traceback (most recent call last):
  File "C:\Users\jbard\google-maps-scraper-pro-master\main.py", line 3, in <module>
    from src import tasks_to_be_run
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\__init__.py", line 1, in <module>
    from .scrape_google_maps_links_task import ScrapeGoogleMapsLinksTask
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 3, in <module>
    from src.scrape_google_maps_places_task import ScrapeGoogleMapsPlacesTask
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 5, in <module>
    class ScrapeGoogleMapsPlacesTask(BaseTask):
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 6, in ScrapeGoogleMapsPlacesTask
    task_config = TaskConfig(output_filename="all",
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskConfig.__init__() got an unexpected keyword argument 'log_time'

My folder looks like this after running `pip install -r requirements.txt`

<img width="222" alt="image" src="https://github.com/omkarcloud/google-maps-scraper/assets/13701124/e50dc55b-fdcd-4733-b9bd-5aadeec1f6fc">

**Comment by Chetan11-dev** [comment]
I kindly request you to run the following command to update the dependencies:

```
python -m pip install bose --upgrade

```
