### ISSUE TITLE
https://goo.gl/maps/2Vd5f8qHL7Xjhha28

### ISSUE THREAD

**Issue by rlxdf** [omkarcloud/google-maps-scraper#5]
Traceback (most recent call last):
  File "/home/rlxdf/.local/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 250, in run
    result = get_data()
             ^^^^^^^^^^
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 241, in get_data
    a = get_maps_data(links)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 220, in get_maps_data
    ls = list(map(get_data, links))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 152, in get_data
    out_dict['title'] = heading.text
                        ^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 84, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.90)
Stacktrace:
#0 0x5613ee72f233 <unknown>
#1 0x5613ee45e8e6 <unknown>
#2 0x5613ee4483a4 <unknown>
#3 0x5613ee4480c0 <unknown>
#4 0x5613ee446adf <unknown>
#5 0x5613ee447282 <unknown>
#6 0x5613ee462761 <unknown>
#7 0x5613ee4645ee <unknown>
#8 0x5613ee4646bc <unknown>
#9 0x5613ee495592 <unknown>
#10 0x5613ee4b9c82 <unknown>
#11 0x5613ee490773 <unknown>
#12 0x5613ee4b9e4e <unknown>
#13 0x5613ee4d1fce <unknown>
#14 0x5613ee4b9a53 <unknown>
#15 0x5613ee48ef4d <unknown>
#16 0x5613ee48ffbe <unknown>
#17 0x5613ee6ef114 <unknown>
#18 0x5613ee6f2f67 <unknown>
#19 0x5613ee6fd6b0 <unknown>
#20 0x5613ee6f3bb3 <unknown>
#21 0x5613ee6c195a <unknown>
#22 0x5613ee7184f8 <unknown>
#23 0x5613ee718687 <unknown>
#24 0x5613ee727f83 <unknown>
#25 0x7fcbafe3bfd4 <unknown>

Traceback (most recent call last):
  File "/home/rlxdf/.local/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 250, in run
    result = get_data()
             ^^^^^^^^^^
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 241, in get_data
    a = get_maps_data(links)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 220, in get_maps_data
    ls = list(map(get_data, links))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/github/google-maps-scraper/src/scraper.py", line 152, in get_data
    out_dict['title'] = heading.text
                        ^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 84, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.90)
Stacktrace:
#0 0x5613ee72f233 <unknown>
#1 0x5613ee45e8e6 <unknown>
#2 0x5613ee4483a4 <unknown>
#3 0x5613ee4480c0 <unknown>
#4 0x5613ee446adf <unknown>
#5 0x5613ee447282 <unknown>
#6 0x5613ee462761 <unknown>
#7 0x5613ee4645ee <unknown>
#8 0x5613ee4646bc <unknown>
#9 0x5613ee495592 <unknown>
#10 0x5613ee4b9c82 <unknown>
#11 0x5613ee490773 <unknown>
#12 0x5613ee4b9e4e <unknown>
#13 0x5613ee4d1fce <unknown>
#14 0x5613ee4b9a53 <unknown>
#15 0x5613ee48ef4d <unknown>
#16 0x5613ee48ffbe <unknown>
#17 0x5613ee6ef114 <unknown>
#18 0x5613ee6f2f67 <unknown>
#19 0x5613ee6fd6b0 <unknown>
#20 0x5613ee6f3bb3 <unknown>
#21 0x5613ee6c195a <unknown>
#22 0x5613ee7184f8 <unknown>
#23 0x5613ee718687 <unknown>
#24 0x5613ee727f83 <unknown>
#25 0x7fcbafe3bfd4 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rlxdf/.local/lib/python3.11/site-packages/bose/bose_driver.py", line 272, in save_screenshot
    self.get_screenshot_as_file(
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 927, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 963, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 975, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/rlxdf/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.90)
Stacktrace:
#0 0x5613ee72f233 <unknown>
#1 0x5613ee45e8e6 <unknown>
#2 0x5613ee447743 <unknown>
#3 0x5613ee4475e3 <unknown>
#4 0x5613ee4600e2 <unknown>
#5 0x5613ee4d1a95 <unknown>
#6 0x5613ee4b9a53 <unknown>
#7 0x5613ee48ef4d <unknown>
#8 0x5613ee48ffbe <unknown>
#9 0x5613ee6ef114 <unknown>
#10 0x5613ee6f2f67 <unknown>
#11 0x5613ee6fd6b0 <unknown>
#12 0x5613ee6f3bb3 <unknown>
#13 0x5613ee6c195a <unknown>
#14 0x5613ee7184f8 <unknown>
#15 0x5613ee718687 <unknown>
#16 0x5613ee727f83 <unknown>
#17 0x7fcbafe3bfd4 <unknown>

Failed to save screenshot
Press Enter To Close Browser

**Comment by Chetan11-dev** [comment]
I'm unable to assist you with your issue as I am busy. I encourage you to try resolving the issue by yourself and post the fix.

Thanks
