### ISSUE TITLE
Charmap - regular failed task

### ISSUE THREAD

**Issue by 007-JB** [omkarcloud/google-maps-scraper#51]
I've been getting this more recently: regardless of the search query (Which, on pro with same connectivity/speed, has slowed significantly compared to when it used to work)..

Result is that tasks fails, no update to output file CSV....

**Config file:**

queries = [
        {"keyword": "restaurants near al sahafah",
         "has phone": True,
         "min_reviews": 100,
         "min_rating": 4.5},
        {"keyword": "used funiture near al rabi",
         "has phone": True,
         "min_reviews": 100,
         "min_rating": 4.5},
]
number_of_scrapers = 12

**Output:**

Traceback (most recent call last):
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 190, in run_task
    result = self.run(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 261, in run
    result = self.parallel(
             ^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 95, in parallel
    result = (Parallel(n_jobs=n, backend="threading")(delayed(run)(l) for l in data_list))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 89, in run
    raise e
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 84, in run
    result = callable(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 160, in save_google
    return ScrapeGoogleMapsPlacesTask().run(driver, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 82, in run
    results = get_maps_data(links)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 76, in get_maps_data
    ls = remove_nones(list(map(get_data, links)))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 73, in get_data
    print('Done: ' + out_dict.get('title', ''))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-27: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 190, in run_task
    result = self.run(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 261, in run
    result = self.parallel(
             ^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 95, in parallel
    result = (Parallel(n_jobs=n, backend="threading")(delayed(run)(l) for l in data_list))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 89, in run
    raise e
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 84, in run
    result = callable(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 160, in save_google
    return ScrapeGoogleMapsPlacesTask().run(driver, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 82, in run
    results = get_maps_data(links)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 76, in get_maps_data
    ls = remove_nones(list(map(get_data, links)))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 73, in get_data
    print('Done: ' + out_dict.get('title', ''))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-11: character maps to <undefined>
Task Started
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Launched Browser
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Scrolling...
Fetched 119 links.
0 https://www.google.com/maps/place/Noodlesta/data=!4m7!3m6!1s0x3e2ee3b3a821fb93:0xe1bb86f8a6097fca!8m2!3d24.7898201!4d46.648781!16s%2Fg%2F11h3g9vdr4!19sChIJk_shqLPjLj4Ryn8JpviGu-E?authuser=0&hl=en&rclk=1
1 https://www.google.com/maps/place/Plov-+%D8%A8%D9%84%D9%88%D9%81+%D8%A8%D8%AE%D8%A7%D8%B1%D9%8A%E2%80%AD/data=!4m7!3m6!1s0x3e2ee3e3b8cf5a87:0xcfcd40de62c8e0fb!8m2!3d24.7890161!4d46.6486717!16s%2Fg%2F11s3qmn5wc!19sChIJh1rPuOPjLj4R--DIYt5Azc8?authuser=0&hl=en&rclk=1
2 https://www.google.com/maps/place/Jones+The+Grocer/data=!4m7!3m6!1s0x3e2ee3a1b0f194ab:0xab9da48fce4b89e1!8m2!3d24.7618125!4d46.6384375!16s%2Fg%2F11v0byxs8s!19sChIJq5TxsKHjLj4R4YlLzo-knas?authuser=0&hl=en&rclk=1
3 https://www.google.com/maps/place/Malga/data=!4m7!3m6!1s0x3e2ee5bc4d870dc1:0x24e46f1673226cec!8m2!3d24.800512!4d46.5983031!16s%2Fg%2F11kqltsv0n!19sChIJwQ2HTbzlLj4R7GwicxZv5CQ?authuser=0&hl=en&rclk=1
4 https://www.google.com/maps/place/Maestro+Pizza/data=!4m7!3m6!1s0x3e2ee315ae7daa21:0x18c8146a2645475b!8m2!3d24.789698!4d46.6490995!16s%2Fg%2F11b6gcfbl4!19sChIJIap9rhXjLj4RW0dFJmoUyBg?authuser=0&hl=en&rclk=1
5 https://www.google.com/maps/place/%D8%B4%D8%AC%D8%B1%D8%A9+%D8%A7%D9%84%D8%B2%D9%8A%D8%AA%D9%88%D9%86%E2%80%AD/data=!4m7!3m6!1s0x3e2ee318c76614e9:0xf4687db70b249b19!8m2!3d24.7853043!4d46.6343212!16s%2Fg%2F11kb7g3rxj!19sChIJ6RRmxxjjLj4RGZskC7d9aPQ?authuser=0&hl=en&rclk=1
6 https://www.google.com/maps/place/Barbar+Al+Yasmin/data=!4m7!3m6!1s0x3e2ee5493b0d449b:0x624d929897fabfe2!8m2!3d24.8226779!4d46.6533941!16s%2Fg%2F11kr9jw4q5!19sChIJm0QNO0nlLj4R4r_6l5iSTWI?authuser=0&hl=en&rclk=1
7 https://www.google.com/maps/place/PSP/data=!4m7!3m6!1s0x3e2ee35fd3ac1429:0x4da78f89f0c22763!8m2!3d24.7756427!4d46.6338867!16s%2Fg%2F11svqgn0pp!19sChIJKRSs01_jLj4RYyfC8ImPp00?authuser=0&hl=en&rclk=1
8 https://www.google.com/maps/place/%D8%A7%D9%88%D9%83%D9%86%D9%88+%D8%AF%D9%88%D8%A7%D9%85%E2%80%AD/data=!4m7!3m6!1s0x3e2ee3a560d6a89d:0x806b791b8166c6e0!8m2!3d24.793224!4d46.653549!16s%2Fg%2F11sv0vfjtb!19sChIJnajWYKXjLj4R4MZmgRt5a4A?authuser=0&hl=en&rclk=1
9 https://www.google.com/maps/place/Shrimp+Shack/data=!4m7!3m6!1s0x3e2ee33f5d738f17:0xb61d87c35f8d81b!8m2!3d24.7937583!4d46.6549949!16s%2Fg%2F11ggqtq511!19sChIJF49zXT_jLj4RG9j4NXzYYQs?authuser=0&hl=en&rclk=1
10 https://www.google.com/maps/place/FLOD+%7C+Healthy+Food/data=!4m7!3m6!1s0x3e2ee3b350490327:0x2b6e08ab1da32f7f!8m2!3d24.7901899!4d46.6485952!16s%2Fg%2F11sj948_05!19sChIJJwNJULPjLj4Rfy-jHasIbis?authuser=0&hl=en&rclk=1
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Launched Browser
Done: Casa Cacao El Celler de Can Roca
Done: HungerHub
Done: MP sandwich
Done: JW Steakhouse
Done: SULTAN AHMET
Done: CROSTA
Done: Sbarro Sahafa
Done: Bahadar154
Done: Pizza hut
Done: TACOSON
Done: 300 Degrees
Done: Al Romansiah
Done: Food Supplies Company Limited
Done: Qasdeer
Done: baodo
Done: Al tarboush al dimashqi restaurant
Done: Achar Chefna Restaurant Riyadh
Done: Om Ali
Done: Kudu
Done: Fork & Pipe
Done: Wafra Al Safwa (Safwa Cuisine)
Done: KATSU SANDO
Done: Shawarma Baker
Done: Burger King - Sahafa
Done: The Food Concept
Done: Buffalo Wild Wings - Sahafa
Done: To fitness
Done: Pasta Delizia
Done: Molto
Done: DAYS BURGER
Done: HARDEE''S
Done: Lulu restaurant
Done: Bellbird
Done: Sastoria
Done: Midori Salad
Closing Browser
Closed Browser
Task Failed! View Final Screenshot at tasks/15/final.png
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844 Safari/537.36
Launched Browser
Fetched 10 links.
Creating Driver with window_size=1920,1080 and user_agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.37
Launched Browser
Done: Largest Used Showroom Riyadh
Done: Computer store
Done: used furniture
Closing Browser
Closed Browser
Task Failed! View Final Screenshot at tasks/16/final.png
Task Completed!

**Final screenshot**

**Not showing most recent search (showing previous which also failed?)**

![image](https://github.com/omkarcloud/google-maps-scraper/assets/13701124/8eea3a38-baff-4398-9209-d6e3390290a0)

**Error Log** (in tasks folder)

Traceback (most recent call last):
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 190, in run_task
    result = self.run(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 261, in run
    result = self.parallel(
             ^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 95, in parallel
    result = (Parallel(n_jobs=n, backend="threading")(delayed(run)(l) for l in data_list))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
                   ^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 89, in run
    raise e
  File "C:\Users\jbard\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 84, in run
    result = callable(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_links_task.py", line 160, in save_google
    return ScrapeGoogleMapsPlacesTask().run(driver, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 82, in run
    results = get_maps_data(links)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 76, in get_maps_data
    ls = remove_nones(list(map(get_data, links)))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbard\google-maps-scraper-pro-master\src\scrape_google_maps_places_task.py", line 73, in get_data
    print('Done: ' + out_dict.get('title', ''))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-11: character maps to <undefined>

**Comment by Chetan11-dev** [comment]
Fixed the Bug, Check "j**********s@gmail.com" for link to Updated Pro Version.
