### ISSUE TITLE
not exactly sure what this issue is related to -  

### ISSUE THREAD

**Issue by salmansarwar5102** [omkarcloud/google-maps-scraper#56]
Traceback (most recent call last):
  File "D:\google-maps-scraper\main.py", line 3, in <module>
    from src import tasks_to_be_run
  File "D:\google-maps-scraper\src\__init__.py", line 1, in <module>
    from .scrape_google_maps_links_task import ScrapeGoogleMapsLinksTask
  File "D:\google-maps-scraper\src\scrape_google_maps_links_task.py", line 5, in <module>
    from src.scrape_google_maps_places_task import ScrapeGoogleMapsPlacesTask
  File "D:\google-maps-scraper\src\scrape_google_maps_places_task.py", line 5, in <module>
    class ScrapeGoogleMapsPlacesTask(BaseTask):
  File "D:\google-maps-scraper\src\scrape_google_maps_places_task.py", line 6, in ScrapeGoogleMapsPlacesTask
    task_config = TaskConfig(output_filename="all",
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskConfig.__init__() got an unexpected keyword argument 'log_time'

**Comment by Chetan11-dev** [comment]
Run the following command to update the dependencies:

```
python -m pip install bose --upgrade
```
