### ISSUE TITLE
Facing error while executing program

### ISSUE THREAD

**Issue by deepaksethi141** [omkarcloud/google-maps-scraper#58]
Hi,
Below is the error I am getting while running the program in the command prompt: 
(I am end user of this program)

Traceback (most recent call last):
  File "I:\1\main.py", line 16, in <module>
    launch_tasks(*tasks_to_be_run)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\launch_tasks.py", line 54, in launch_tasks
    current_output = task.begin_task(current_data, task_config)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\base_task.py", line 249, in begin_task
    final = run_task(False, 0)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\base_task.py", line 190, in run_task
    create_directories(self.task_path)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\base_task.py", line 134, in create_directories
    _download_driver()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\base_task.py", line 34, in _download_driver
    download_driver()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\download_driver.py", line 50, in download_driver
    download_driver_in_path()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bose\download_driver.py", line 12, in download_driver_in_path
    path = chromedriver_autoinstaller_fix.install(path='build/')
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chromedriver_autoinstaller_fix\__init__.py", line 21, in install
    chromedriver_filepath = utils.download_chromedriver(path, no_ssl)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chromedriver_autoinstaller_fix\utils.py", line 283, in download_chromedriver
    major_version = get_major_version(chromedriver_version)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\chromedriver_autoinstaller_fix\utils.py", line 212, in get_major_version
    return version.split(".")[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Chetan11-dev** [comment]
Do you have Chrome installed?

**Comment by deepaksethi141** [comment]
I have checked and updated chrome as due to some reason it was not auto updating.
Let me rerun the program

**Comment by deepaksethi141** [comment]
The program ran! it seems phone numbers are not being scraped. Any reason behind that

**Comment by Chetan11-dev** [comment]
it's in pro persion.

**Comment by deepaksethi141** [comment]
Please provide your whatsapp number?

**Comment by Chetan11-dev** [comment]
https://wa.me/message/3WED4FYQRDPNE1

**Comment by Chetan11-dev** [comment]
@deepaksethi141, We released new Version. Kindly use it.
