### ISSUE TITLE
Bug on complete address

### ISSUE THREAD

**Issue by M0in4** [omkarcloud/google-maps-scraper#63]
Used config:
queries = [
    {
        "keyword": "bar delphi",
        "select": ["title", "main_category", "phone" , "complete_address" "categories"],
    },
]

number_of_scrapers = 16

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/bose/base_task.py", line 220, in run_task
    result = self.run(driver, data)
  File "/Users/xx/Documents/xx/Google Maps Scraper/google-maps-scraper-pro-master/src/scrape_google_maps_links_task.py", line 302, in run
    new_results = clean(fetched_results, data)
  File "/Users/xx/Documents/xx/Google Maps Scraper/google-maps-scraper-pro-master/src/scrape_google_maps_links_task.py", line 142, in clean
    new_results = [sort_dict_by_keys(x, keys) for x in new_results]
  File "/Users/xx/Documents/xx/Google Maps Scraper/google-maps-scraper-pro-master/src/scrape_google_maps_links_task.py", line 142, in <listcomp>
    new_results = [sort_dict_by_keys(x, keys) for x in new_results]
  File "/Users/xx/Documents/xx/Google Maps Scraper/google-maps-scraper-pro-master/src/scrape_google_maps_links_task.py", line 100, in sort_dict_by_keys
    new_dict[key] = dictionary[key]
KeyError: 'complete_addresscategories'

**Comment by Chetan11-dev** [comment]
Config is wrong, Should be
```
queries = [
    {
        "keyword": "bar delphi",
        "select": ["title", "main_category", "phone", "complete_address", "categories"],
    }
]

```
