### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by bkpp123** [omkarcloud/google-maps-scraper#67]
**sorry I got this issue when running 'python main.py '
and I did not change anything in the main.py:**

from src.gmaps import Gmaps
star_it = '''Love It? Star It! ⭐ https://github.com/omkarcloud/google-maps-scraper/'''
queries = ["web developers in delhi"]
Gmaps.places(queries, max=5)

**But got this error:** 

(scraper) C:\Users\mf202\google-maps-scraper-master>python main.py
Running
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.gmaps import Gmaps
  File "C:\Users\mf202\google-maps-scraper-master\src\gmaps.py", line 6, in <module>
    from .cities import Cities
  File "C:\Users\mf202\google-maps-scraper-master\src\cities.py", line 94, in <module>
    class Cities:
  File "C:\Users\mf202\google-maps-scraper-master\src\cities.py", line 95, in Cities
    Afghanistan = create_city_handler("AF")
  File "C:\Users\mf202\google-maps-scraper-master\src\cities.py", line 76, in create_city_handler
    def handle_city_data(_, prepend: str) -> list[str]:
TypeError: 'type' object is not subscriptable

**Comment by Chetan11-dev** [comment]
Maybe due to python version that does not support typehints,
So follow https://github.com/omkarcloud/google-maps-scraper/blob/master/advanced.md#-i-dont-have-python-or-im-facing-errors-when-setting-up-the-scraper-on-my-pc-how-to-solve-it
