### ISSUE TITLE
No chrome executable found on PATH

### ISSUE THREAD

**Issue by venkatish1992** [omkarcloud/google-maps-scraper#68]
Traceback (most recent call last):
  File "/home/ubuntu/google-maps-scraper/main.py", line 5, in <module>
    Gmaps.places(queries, max=5)
  File "/home/ubuntu/google-maps-scraper/src/gmaps.py", line 312, in places
    places_obj = scraper.scrape_places(place_data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/decorators.py", line 286, in wrapper_browser
    check_and_download_driver()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/check_and_download_driver.py", line 21, in check_and_download_driver
    if not has_driver():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/check_and_download_driver.py", line 10, in has_driver
    driver_path =  relative_path(get_driver_path(), 0)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/get_chrome_version.py", line 361, in get_driver_path
    executable_name = get_filename(_get_major_version())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/get_chrome_version.py", line 353, in _get_major_version
    version = get_major_version(get_chrome_version())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/get_chrome_version.py", line 135, in get_chrome_version
    path = get_linux_executable_path()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/botasaurus/get_chrome_version.py", line 199, in get_linux_executable_path
    raise ValueError("No chrome executable found on PATH")
ValueError: No chrome executable found on PATH

**Comment by Chetan11-dev** [comment]
You don't have chrome installed, install it.

**Comment by venkatish1992** [comment]
i have added chrome driver to the path on ubuntu 22.04 still same error msg

**Comment by venkatish1992** [comment]
fixed it Thanks

**Comment by venkatish1992** [comment]
Thanks
