### ISSUE TITLE
Getting Error Please Suggest..

### ISSUE THREAD

**Issue by vivekkadia** [omkarcloud/google-maps-scraper#79]
Running
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/decorators.py", line 361, in run_task
    result = func(driver, data)
  File "/var/www/172-234-140-37.ip.linodeusercontent.com/public_html/google-maps-scraper/src/scraper.py", line 257, in scrape_places
    perform_visit(driver, search_link)
  File "/var/www/172-234-140-37.ip.linodeusercontent.com/public_html/google-maps-scraper/src/scraper_utils.py", line 26, in perform_visit
    visit_gmap_with_consent()
  File "/var/www/172-234-140-37.ip.linodeusercontent.com/public_html/google-maps-scraper/src/scraper_utils.py", line 6, in visit_gmap_with_consent
    driver.organic_get(link, accept_cookies=True)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 325, in organic_get
    accept_google_cookies(self)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/accept_google_cookies.py", line 25, in accept_google_cookies
    raise Exception("Unabe to load Google")
Exception: Unabe to load Google
Task failed with data: {'query': 'web developers in bangalore', 'is_spending_on_ads': False, 'max': 5, 'lang': None, 'geo_coordinates': None, 'zoom': None, 'convert_to_english': True}
Traceback (most recent call last):
  File "/var/www/172-234-140-37.ip.linodeusercontent.com/public_html/google-maps-scraper/main.py", line 10, in <module>
    Gmaps.places(queries, max=5)
  File "/var/www/172-234-140-37.ip.linodeusercontent.com/public_html/google-maps-scraper/src/gmaps.py", line 325, in places
    result_item = process_result(min_reviews, max_reviews, category_in, has_website, has_phone, min_rating, max_rating, sort, key, scrape_reviews, reviews_max, reviews_sort, fields, lang, should_scrape_socials, convert_to_english,use_cache,places_obj)
  File "/var/www/172-234-140-37.ip.linodeusercontent.com/public_html/google-maps-scraper/src/gmaps.py", line 181, in process_result
    places = places_obj["places"]
TypeError: 'NoneType' object is not subscriptable

**Comment by vivekkadia** [comment]
Previous version was so tuned but after update on last week. i am getting many errors..

**Comment by vivekkadia** [comment]
@Chetan11-dev Please do the needful brother :)

**Comment by vivekkadia** [comment]
> Previous version was so tuned but after update on last week. i am getting many errors..

Thanks to confirm :)

**Comment by Chetan11-dev** [comment]
Unable to reproduce it, Could you run 
```
python -m pip install botasaurus --upgrade
```
And Let me know if it occurs again?

**Comment by guan-yuan** [comment]
> Unable to reproduce it, Could you run
> 
> ```
> python -m pip install botasaurus --upgrade
> ```
> 
> And Let me know if it occurs again?

I got the same error (after python -m pip install botasaurus --upgrade)

Additionally, it is suggested that in botasaurus\utils.py, the read_json function can include encoding="utf-8". Otherwise, in some language environments on Windows, there might be errors.

```
def read_json(path):
    with open(path, 'r', encoding="utf-8") as fp:
        data = json.load(fp)
        return data
```

**Comment by Chetan11-dev** [comment]
I can't reproduce bug, so follow https://github.com/omkarcloud/google-maps-scraper/blob/master/advanced.md#-i-dont-have-python-or-im-facing-errors-when-setting-up-the-scraper-on-my-pc-how-to-solve-it for now

**Comment by guan-yuan** [comment]
After I removed the cache, it seems to be working normally

**Comment by guan-yuan** [comment]
> Share `error_log/` folder zip file

[error_logs.zip](https://github.com/omkarcloud/google-maps-scraper/files/13674540/error_logs.zip)

The error occurred again, so I provided a zip file of the error_log for reference. Thank you.

**Comment by Chetan11-dev** [comment]
Fixed, Please follow these Steps. 

⿡ Clone the Magic 🧙‍♀:
```
git clone https://github.com/omkarcloud/google-maps-scraper
cd google-maps-scraper
```

⿢ Install Dependencies 📦:
```
python -m pip install -r requirements.txt
```

⿣ Let the Rain of Google Map Leads Begin 😎:
```
python main.py 
```
