### ISSUE TITLE
ModuleNotFoundError: No module named 'botasaurus'

### ISSUE THREAD

**Issue by salmansarwar5102** [omkarcloud/google-maps-scraper#86]
`$ python3 main.py
Traceback (most recent call last):
  File "/home/salman/site/google-maps-scraper/main.py", line 1, in <module>
    from src.gmaps import Gmaps
  File "/home/salman/site/google-maps-scraper/src/gmaps.py", line 1, in <module>
    from botasaurus import bt
ModuleNotFoundError: No module named 'botasaurus'
`

**Comment by Chetan11-dev** [comment]
Run ```python -m pip install botasaurus --upgrade```

**Comment by salmansarwar5102** [comment]
after installing botasaurus, this is the output.

```python
salman@salman-VirtualBox:~/site/google-maps-scraper$ python3 main.py
Traceback (most recent call last):
  File "/home/salman/site/google-maps-scraper/main.py", line 1, in <module>
    from src.gmaps import Gmaps
  File "/home/salman/site/google-maps-scraper/src/gmaps.py", line 3, in <module>
    from src import scraper
  File "/home/salman/site/google-maps-scraper/src/scraper.py", line 5, in <module>
    from src.utils import convert_unicode_dict_to_ascii_dict, unique_strings
  File "/home/salman/site/google-maps-scraper/src/utils.py", line 2, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

```

**Comment by salmansarwar5102** [comment]
its working now. tysm :)
