### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by vivekkadia** [omkarcloud/google-maps-scraper#95]
root@172-235-26-138:/var/www/172-235-26-138.ip.linodeusercontent.com/public_html/google-maps-scraper# python main.py
Running
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 77, in retry_if_is_error
    created_result = func()
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 12, in <lambda>
    lambda: do_create_driver(tiny_profile, profile, window_size, user_agent, proxy, is_eager, headless, lang, block_resources, block_images, beep),
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 301, in do_create_driver
    driver = create_selenium_driver(proxy, options, desired_capabilities, path)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 227, in create_selenium_driver
    driver = AntiDetectDriver(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x558863bbbf83 <unknown>
#1 0x558863874cf7 <unknown>
#2 0x5588638ac60e <unknown>
#3 0x5588638a926e <unknown>
#4 0x5588638f980c <unknown>
#5 0x5588638ede53 <unknown>
#6 0x5588638b5dd4 <unknown>
#7 0x5588638b71de <unknown>
#8 0x558863b80531 <unknown>
#9 0x558863b84455 <unknown>
#10 0x558863b6cf55 <unknown>
#11 0x558863b850ef <unknown>
#12 0x558863b5099f <unknown>
#13 0x558863ba9008 <unknown>
#14 0x558863ba91d7 <unknown>
#15 0x558863bbb124 <unknown>
#16 0x7fc34ea14ac3 <unknown>

Retrying
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 77, in retry_if_is_error
    created_result = func()
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 12, in <lambda>
    lambda: do_create_driver(tiny_profile, profile, window_size, user_agent, proxy, is_eager, headless, lang, block_resources, block_images, beep),
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 301, in do_create_driver
    driver = create_selenium_driver(proxy, options, desired_capabilities, path)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 227, in create_selenium_driver
    driver = AntiDetectDriver(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559e9d429f83 <unknown>
#1 0x559e9d0e2cf7 <unknown>
#2 0x559e9d11a60e <unknown>
#3 0x559e9d11726e <unknown>
#4 0x559e9d16780c <unknown>
#5 0x559e9d15be53 <unknown>
#6 0x559e9d123dd4 <unknown>
#7 0x559e9d1251de <unknown>
#8 0x559e9d3ee531 <unknown>
#9 0x559e9d3f2455 <unknown>
#10 0x559e9d3daf55 <unknown>
#11 0x559e9d3f30ef <unknown>
#12 0x559e9d3be99f <unknown>
#13 0x559e9d417008 <unknown>
#14 0x559e9d4171d7 <unknown>
#15 0x559e9d429124 <unknown>
#16 0x7feab56e1ac3 <unknown>

Retrying
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 77, in retry_if_is_error
    created_result = func()
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 12, in <lambda>
    lambda: do_create_driver(tiny_profile, profile, window_size, user_agent, proxy, is_eager, headless, lang, block_resources, block_images, beep),
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 301, in do_create_driver
    driver = create_selenium_driver(proxy, options, desired_capabilities, path)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 227, in create_selenium_driver
    driver = AntiDetectDriver(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x560ddf8c8f83 <unknown>
#1 0x560ddf581cf7 <unknown>
#2 0x560ddf5b960e <unknown>
#3 0x560ddf5b626e <unknown>
#4 0x560ddf60680c <unknown>
#5 0x560ddf5fae53 <unknown>
#6 0x560ddf5c2dd4 <unknown>
#7 0x560ddf5c41de <unknown>
#8 0x560ddf88d531 <unknown>
#9 0x560ddf891455 <unknown>
#10 0x560ddf879f55 <unknown>
#11 0x560ddf8920ef <unknown>
#12 0x560ddf85d99f <unknown>
#13 0x560ddf8b6008 <unknown>
#14 0x560ddf8b61d7 <unknown>
#15 0x560ddf8c8124 <unknown>
#16 0x7f1f2a0c2ac3 <unknown>

Retrying
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 77, in retry_if_is_error
    created_result = func()
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 12, in <lambda>
    lambda: do_create_driver(tiny_profile, profile, window_size, user_agent, proxy, is_eager, headless, lang, block_resources, block_images, beep),
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 301, in do_create_driver
    driver = create_selenium_driver(proxy, options, desired_capabilities, path)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 227, in create_selenium_driver
    driver = AntiDetectDriver(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55687f6dbf83 <unknown>
#1 0x55687f394cf7 <unknown>
#2 0x55687f3cc60e <unknown>
#3 0x55687f3c926e <unknown>
#4 0x55687f41980c <unknown>
#5 0x55687f40de53 <unknown>
#6 0x55687f3d5dd4 <unknown>
#7 0x55687f3d71de <unknown>
#8 0x55687f6a0531 <unknown>
#9 0x55687f6a4455 <unknown>
#10 0x55687f68cf55 <unknown>
#11 0x55687f6a50ef <unknown>
#12 0x55687f67099f <unknown>
#13 0x55687f6c9008 <unknown>
#14 0x55687f6c91d7 <unknown>
#15 0x55687f6db124 <unknown>
#16 0x7f606c522ac3 <unknown>

Retrying
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 77, in retry_if_is_error
    created_result = func()
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 12, in <lambda>
    lambda: do_create_driver(tiny_profile, profile, window_size, user_agent, proxy, is_eager, headless, lang, block_resources, block_images, beep),
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 301, in do_create_driver
    driver = create_selenium_driver(proxy, options, desired_capabilities, path)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 227, in create_selenium_driver
    driver = AntiDetectDriver(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x564622184f83 <unknown>
#1 0x564621e3dcf7 <unknown>
#2 0x564621e7560e <unknown>
#3 0x564621e7226e <unknown>
#4 0x564621ec280c <unknown>
#5 0x564621eb6e53 <unknown>
#6 0x564621e7edd4 <unknown>
#7 0x564621e801de <unknown>
#8 0x564622149531 <unknown>
#9 0x56462214d455 <unknown>
#10 0x564622135f55 <unknown>
#11 0x56462214e0ef <unknown>
#12 0x56462211999f <unknown>
#13 0x564622172008 <unknown>
#14 0x5646221721d7 <unknown>
#15 0x564622184124 <unknown>
#16 0x7fe87b411ac3 <unknown>

Traceback (most recent call last):
  File "/var/www/172-235-26-138.ip.linodeusercontent.com/public_html/google-maps-scraper/main.py", line 9, in <module>
    Gmaps.places(queries, max=5)
  File "/var/www/172-235-26-138.ip.linodeusercontent.com/public_html/google-maps-scraper/src/gmaps.py", line 339, in places
    places_obj = scraper.scrape_places(place_data, cache = use_cache)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/decorators.py", line 450, in wrapper_browser
    current_result = run_task(data_item, False, 0)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/decorators.py", line 363, in run_task
    driver = creators.create_driver(tiny_profile, evaluated_profile, evaluated_window_size, evaluated_user_agent, evaluated_proxy, is_eager, evaluated_headless, evaluated_lang, block_resources, block_images, beep)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 11, in create_driver
    return retry_if_is_error(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 95, in retry_if_is_error
    raise e
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/utils.py", line 77, in retry_if_is_error
    created_result = func()
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/creators.py", line 12, in <lambda>
    lambda: do_create_driver(tiny_profile, profile, window_size, user_agent, proxy, is_eager, headless, lang, block_resources, block_images, beep),
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 301, in do_create_driver
    driver = create_selenium_driver(proxy, options, desired_capabilities, path)
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/create_driver_utils.py", line 227, in create_selenium_driver
    driver = AntiDetectDriver(
  File "/usr/local/lib/python3.10/dist-packages/botasaurus/anti_detect_driver.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x564622184f83 <unknown>
#1 0x564621e3dcf7 <unknown>
#2 0x564621e7560e <unknown>
#3 0x564621e7226e <unknown>
#4 0x564621ec280c <unknown>
#5 0x564621eb6e53 <unknown>
#6 0x564621e7edd4 <unknown>
#7 0x564621e801de <unknown>
#8 0x564622149531 <unknown>
#9 0x56462214d455 <unknown>
#10 0x564622135f55 <unknown>
#11 0x56462214e0ef <unknown>
#12 0x56462211999f <unknown>
#13 0x564622172008 <unknown>
#14 0x5646221721d7 <unknown>
#15 0x564622184124 <unknown>
#16 0x7fe87b411ac3 <unknown>

**Comment by vivekkadia** [comment]
any update on this error please?

**Comment by psirdev** [comment]
Don't use this on root.

Add user and sudoers + ubuntu 23.04, it worked like a charm.

**Comment by Chetan11-dev** [comment]
You are using on linode, I recommend running it in Docker.
