### ISSUE TITLE
WSL2 error : TypeError: request() got an unexpected keyword argument 'use_stealth'

### ISSUE THREAD

**Issue by salmansarwar5102** [omkarcloud/google-maps-scraper#99]
Gmaps.places(queries, max=5)sam@LAPTOP-S5LCRFHR:~/site/google-maps-scraper$ python3 main.py
Traceback (most recent call last):
  File "/home/sam/site/google-maps-scraper/main.py", line 1, in <module>
    from src import Gmaps
  File "/home/sam/site/google-maps-scraper/src/__init__.py", line 1, in <module>
    from .gmaps import Gmaps
  File "/home/sam/site/google-maps-scraper/src/gmaps.py", line 3, in <module>
    from src import scraper
  File "/home/sam/site/google-maps-scraper/src/scraper.py", line 89, in <module>
    @request(
TypeError: request() got an unexpected keyword argument 'use_stealth'

**Comment by Chetan11-dev** [comment]
Thank you, @salmansarwar5102, for opening the issue and using our Google Maps Scraper Tool.
   Also, you may run followin command to fix your issues
   ```
   python -m pip install botasaurus --upgrade
   ```
